export { default as NavBar } from './NavBar/NavBar'
export { default as Routes } from './App/Routes'
export { default as Home } from './Home/Home'
export { default as About } from './About/About'
export { default as Services } from './Services/Services'
export { default as Contact } from './Contact/Contact'
export { default as Footer } from './Footer/Footer'
export { default as Carousel } from './Components/Carousel'
